<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
    	<?php foreach ($productList as $product) : ?>
    	<tr>
    		<td>
    			<img src="<?= $wwwUrl ?>/<?= $product["image"]; ?>" alt=""/>
    		</td>
    		<td>
    			<strong><?= $product["name"]; ?></strong>
    			<p><?= $product["description"]; ?></p>
    		</td>
    		<td>
    			<strong><?= Tools::getPrettyPrice($product["priceHT"]); ?> €
                </strong>
    		</td>
    	</tr>

    	<?php endforeach; ?>

	</tbody>

</table>