 <h2><i class="fa fa-check"></i> Payer la commande</h2>

<section class="invoice">
    <p><strong><?= $userById["firstname"];?></strong></p>
    <p><?= $userById["lastname"];?></p>
    <p><?= $userById["zipcode"];?> <span class="city"><?= $userById["city"];?></span></p>
</section>

<table class="generic-table meal-list">
    <caption>Récapitulatif de la commande</caption>
    <thead>
        <tr>
            <th>Nom</th>
            <th>Quantité</th>
            <th>Prix Unitaire</th>
            <th>Prix Total</th>
        </tr>
    </thead>
    <tbody>
           <?php foreach ($products as $product): ?>



            <tr>
                <td>
                <img src="<?= $wwwUrl ?>/<?= $product["image"]; ?>" alt=""/> 

                <?= $product['name'] ?>
                </td>
                <td><?= $product['quantity'] ?></td>
                <td><?= Tools::getPriceTTC($product['priceHT']) ?> €</td>
                <td><?= Tools::getPrettyPrice($product['priceHT'] * $product['quantity']) ?> €</td>
            </tr>

        <?php endforeach ?>
     </tbody>
      <tfoot>
        <tr>
            <td></td>
            <td colspan="2">Total HT :</td>
            <td><?= $totalHT; ?> €</td>
        </tr>
        <tr>
            <td></td>
            <td colspan="2">TVA (20 %) :</td>
            <td><?= number_format($totalHT * 0.20,2); ?> €</td>
        </tr>
        <tr>
            <td></td>
            <td class="colorful" colspan="2">Total TTC :</td>
            <td class="colorful"><?= number_format($totalHT*1.2,2); ?> €</td>
        </tr>
    </tfoot>
</table>

<hr>
<h3>Merci de bien vouloir procéder au paiement de la commande.</h3>
<form class="generic-form" action="<?= $requestUrl ?>/Success" method="POST">
	<ul>
		<li>
            <input type="hidden" name="order_id" value="<?= $orderById["id"]; ?>"/>
			<input class="button button-primary" type="submit" value="Payer">
			<a class="button button-cancel small" href="/dev/resto/final/index.php">Annuler</a>
		</li>
	</ul>
</form>    </main>
