 <h2><i class="fa fa-check"></i> Payer la commande</h2>

<section class="invoice">
    <p><strong><?= $userById["firstname"];?></strong></p>
    <p><?= $userById["lastname"];?></p>
    <p><?= $userById["zipcode"];?> <span class="city"><?= $userById["city"];?></span></p>
</section>

<table class="generic-table meal-list">
    <caption>Récapitulatif de la commande</caption>
    <thead>
        <tr>
            <th>Nom</th>
            <th>Quantité</th>
            <th>Prix Unitaire</th>
            <th>Prix Total</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td></td>
            <td colspan="2">Total HT</td>
            <td>36.00 €</td>
        </tr>
        <tr>
            <td></td>
            <td colspan="2">TVA (20 %)</td>
            <td>7.20 €</td>
        </tr>
        <tr>
            <td></td>
            <td class="colorful" colspan="2">Total TTC</td>
            <td class="colorful">43.20 €</td>
        </tr>
    </tfoot>
    <tbody>
           <?php foreach ($products as $product): ?>



            <tr>
                
                <td><?= $product['name'] ?></td>
                <td><?= $product['quantity'] ?></td>
                <td><?= Tools::getPriceTTC($product['priceHT']) ?> €</td>
                <td><?= Tools::getPrettyPrice($product['priceHT'] * $product['quantity']) ?> €</td>
            </tr>

        <?php endforeach ?>
     </tbody>
</table>

<hr>
<h3>Merci de bien vouloir procéder au paiement de la commande.</h3>
<form class="generic-form" action="/dev/resto/final/index.php/order/payment" method="POST">
	<ul>
		<li>
			<input class="button button-primary" type="submit" value="Payer">
			<a class="button button-cancel small" href="/dev/resto/final/index.php">Annuler</a>
		</li>
	</ul>
</form>    </main>
