<h2><i class="fa fa-shopping-cart"></i> Passer une commande</h2>

<form data-order-step="run" id="order-form" class="generic-form">

    <!-- Champ caché stockant le prix de vente du produit alimentaire sélectionné -->
    <input type="hidden" name="salePrice">

    <aside class="error-message hidden">
        <h3><i class="fa fa-warning"></i> Il y a <em class="total-error-count">1</em> erreur(s) dans le formulaire !</h3>
        <p></p>
    </aside>



    <fieldset>
        <legend>Ajouter un article</legend>
        <ul>
            <li>
                <label for="meal">Nom :</label>
                <select id="meal" name="meal">
                <?php foreach($productList as $product) : ?>
                    <option value="<?= $product["id"];?>"><?= $product["name"];?></option>
                <?php endforeach; ?>
                </select>
                <article id="meal-details" class="meal-details no-left-label">
                    <img src="" alt="">
                    <p class="meal-name"></p>
                    <span>Prix: <strong></strong></span><br><br><br>
                    <span>Stock: <em style="color:green;font-weight:bold;"></em></span>
                </article>
            </li>
            <li>
                <label for="quantity">Quantité :</label>
                <input id="quantity" class="quantity" type="text" maxlength="2" name="quantity" data-name="Quantité" data-type="positive-integer" data-required>
            </li>
            <li>
                <button id="btn-add" class="button button-primary no-left-label" type="submit">Ajouter</button>
            </li>
        </ul>
    </fieldset>

    <fieldset>
        <legend>Récapitulatif de la commande</legend>
        <section id="order-summary">
            <table class="generic-table">
                <tbody>
                    <tr>
                    <th>Quantité: </th>
                    <th>Produit: </th>
                    <th>Prix HT: </th>
                    <th>Prix TTC: </th>
                    </tr>
                    <tr>
                        <td class="basket-empty">Votre panier est vide</td>
                    </tr>
                    <tr>
                        <td class="quantity_meal"></td>
                    </tr>

                </tbody>
            </table>
        </section>
    </fieldset>


    <ul class="link-list2">
        <li>
            <button id="validate-order" class="button button-primary" >Valider la commande</button>
            <a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
        </li>
    </ul>
</form>

<script src="<?= $wwwUrl ?>/js/utilities.js"></script>
<script src="<?= $wwwUrl ?>/js/order.js"></script>