<h2><i class="fa fa-lock"></i> Se connecter avec un compte utilisateur</h2>

<form class="generic-form" action="" method="POST">
	
	<?php if (isset($errorMessage)) : ?>
		<aside class="error-message">
		<h3><i class="fa fa-warning"></i><em class="total-error-count"><?= $errorMessage; ?></em></h3>
		<p></p>
	</aside>

	<?php endif; ?>
	

	<fieldset>
		<legend>Informations d'authentification</legend>
		<ul>
			<li>
				<label for="email">E-mail :</label>
				<input id="email" type="text" name="email" data-required data-name="email" value="">
			</li>
			<li>
				<label for="password">Mot de passe :</label>
				<input id="password" type="password" name="password" data-required data-name="Mot de passe">
			</li>
		</ul>
	</fieldset>

	<ul>
		<li>
			<input class="button button-primary" name="submit" type="submit" value="Connexion">
			<a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
		</li>
	</ul>
</form>